#!/bin/bash

# convert jupyter notebooks into executable python and adds hashbang

#TEMPLATE=`mktemp`

# create the template and remove any Jupyter Notebook magic commands
# see: https://github.com/ipython/ipython/issues/3707
#cat <<EOT >> $TEMPLATE
#!/usr/bin/env python
#{% extends "python.tpl"%}
## Comments out magic statement
#{% block codecell %}
#{{  super().replace('get_ipython','#get_ipython') if "get_ipython" in super() else super() }}
#{% endblock codecell %}
#EOT

#if [[ "$VIRTUAL_ENV" != "" ]]
#then
  if [[ $1 != "" ]];
  then
    filename=$(basename -- $1)
    extension="${filename##*.}"
    filename="${filename%.*}"

    jupyter nbconvert --to markdown $1 --stdout > $filename.md

  else
    echo "converts ipython notebooks directly to executable python .py scripts"
    echo "error: no .ipynb specified"
    echo "usage: $ nbconvert my_notebook.ipynb"
  fi
#else
#  echo "this script must be run with the python virtual environment with jupyter avialable"
#  echo "$ source ~/Virtualenvs/python2/bin/activate"
#  exit
#fi
