#!/usr/bin/env zsh

# convert jupyter notebooks into executable python and adds hashbang

TEMPLATE=`mktemp`

# create the template and remove any Jupyter Notebook magic commands
# see: https://github.com/ipython/ipython/issues/3707
cat <<EOT >> $TEMPLATE
#!/usr/bin/env python
{% extends "python.tpl"%}
## Comments out magic statement
{% block codecell %}
{{  super().replace('get_ipython','#get_ipython') if "get_ipython" in super() else super() }}
{% endblock codecell %}
EOT

echo $0, $1, $2

# check for a supplied file
if [[ $1 != "" ]];
then
  if [[ $2 != "" ]];
  then
    outpath=$2
  else
    outpath='./'
  fi

  filename=$(basename -- $1)
  extension="${filename##*.}"
  filename="${filename%.*}"

  jupyter nbconvert --to python $1 --stdout --template=$TEMPLATE > $outpath/$filename.py

else
  echo "converts ipython notebooks directly to executable python .py scripts"
  echo "error: no .ipynb specified"
  echo "$0 [NOTEBOOK File] [optional: output path]"
  echo "usage: $ nbconvert my_notebook.ipynb "
fi
